
include_name: buffer_config
# pipeline: [includes/dataset_augmented_data_recipe.yaml]
include: [includes/dataset_augmented_data_recipe.yaml]
demodulation: true
demodulation_mode: "brdf"
dual: false
scale_regex: 
  ds_scale:
    enable: false
    pattern: "%ds"
    target: "d{}"
    value: null
  aa_scale:
    enable: false
    pattern: "%aa"
    target: "a{}"
    value: null
engine_buffer: {
  "BaseColor": {"suffix": "EXR"},
  "BrdfColor": {"suffix": "EXR"},
  "MetallicRoughnessSpecular": {"suffix": "EXR"},
  "NoVSTAlpha": {"suffix": "EXR"},
  "SceneColorNoST": {"suffix": "EXR"},
  "SceneColor": {"suffix": "EXR"},
  "SkyboxMask": {"suffix": "EXR"},
  "SkyColor": {"suffix": "EXR"},
#   "VelocityDepth_u2": {"suffix": "EXR"},
  "VelocityDepth": {"suffix": "EXR"},
  "WorldNormal": {"suffix": "EXR"},
  "WorldPosition": {"suffix": "EXR"},
}
history_buffer: {

}
output_buffer: {
    "base_color": {"origin": "BaseColor","channel": [0, 1, 2]},
    "brdf_color": {"origin": "BrdfColor","channel": [0, 1, 2]},
    "metallic": {"origin": "MetallicRoughnessSpecular","channel": [0]},
    "roughness": {"origin": "MetallicRoughnessSpecular","channel": [1]},
    "specular": {"origin": "MetallicRoughnessSpecular","channel": [2]},
    "nov": {"origin": "NoVSTAlpha","channel": [0]},
    "st_alpha": {"origin": "NoVSTAlpha","channel": [1]},
    "scene_color": {"origin": "SceneColor","channel": [0, 1, 2]},
    "scene_color_no_st": {"origin": "SceneColorNoST","channel": [0, 1, 2]},
    "skybox_mask": {"origin": "SkyboxMask","channel": [1]},
    "sky_color": {"origin": "SkyColor","channel": [0, 1, 2]},
    "motion_vector": {"origin": "VelocityDepth","channel": [0, 1]},
    "depth": {"origin": "VelocityDepth","channel": [2]},
    "world_normal": {"origin": "WorldNormal","channel": [0, 1, 2]},
    "world_position": {"origin": "WorldPosition","channel": [0, 1, 2]},
}
augmented_data_on_the_fly: [
    # "skybox_mask",
    # "scene_light_no_st",
    # "st_color",
]
metadata_part: "metadata"
basic_part_enable_list: [
    metadata,
    base_color,
    gbuffer,
    # scene_color,
    scene_color_no_st,
    skybox_mask,
    sky_color,
    st,
    depth,
    motion_vector,
    world_normal,
    world_position,
    nov,
    # brdf_color,
]
addition_part_enable_list: [
    # extranet,
    # extranet_fast,
]
part: {
    "metadata":   {
        "type": "fp32",
        "buffer_name": [
            "metadata",
        ],
    },
    "base_color": { 
        "type": "fp16",
        "buffer_name": [
            "base_color",
        ],
    },
    "brdf_color": { 
        "type": "fp16",
        "buffer_name": [
            "brdf_color",
        ],
    },
    "gbuffer": { 
        "type": "fp16",
        "buffer_name": [
            "roughness",
            "specular",
            "metallic"
        ],
    },
    "scene_color": { 
        "type": "fp16",
        "buffer_name": [
            "scene_color",
        ],
    },
    "scene_color_no_st": { 
        "type": "fp16",
        "buffer_name": [
            "scene_color_no_st",
        ],
    },
    "skybox_mask": { 
        "type": "fp16",
        "buffer_name": [
            "skybox_mask",
        ],
    },
    "sky_color": {
        "type": "fp16",
        "buffer_name": [
            "sky_color",
        ],
    },
    "st": { 
        "type": "fp16",
        "buffer_name": [
            "st_color",
            "st_alpha",
        ],
    },
    "depth": { 
        "type": "fp16",
        "buffer_name": [
            "depth",
        ],
    },
    "motion_vector": { 
        "type": "fp16",
        "buffer_name": [
            "motion_vector",
        ],
    },
    "world_normal": { 
        "type": "fp16",
        "buffer_name": [
            "world_normal",
        ],
    },
    "nov": { 
        "type": "fp16",
        "buffer_name": [
            "nov",
        ],
    },
    "world_position": { 
        "type": "fp16",
        "buffer_name": [
            "world_position",
        ],
    },
}