job_name: "export"
config_root_path: "config/"
base: "includes/dataset_export_job.yaml"
pipeline: []
include: ["includes/dataset_export_data_st_aa.yaml"]
dataset:
    scale_config:
        aa_scale: 16
        ds_scale: 2